### ISSUE TITLE
Failed to read an IC card

### ISSUE THREAD

**Issue by shugo-chara** [soralis0912/magisk-module-vili-jp-felica#1]
このプロジェクトは大変助かりました。
持っているxiaomiスマホはおサイフケータイを使いたいので、このプロジェクトを見つかりました。
magisk modを修正して無事インストール出来ました。
が。。おサイフケータイアプリを開くと、「Failed to read an IC card.If you tap anIC card,retry after releasing the IC card.If you dont tap an IC card,turn off Setings of automatically read IC card balance(030203)」というエラーが表示されました。
スマホのNFC設定を見ると、ちゃんとFelicaを選んでいます。

自分はmix fold2に使っているので、ROMはCNバージョンです。調べると、この機種はFelica対応されたはずなのに、いろいろ試すとだめでした。。

**Comment by soralis0912** [comment]
@shugo-chara こちらのモジュールは標準でFelicaが搭載されているデバイスで使えるようにするためのものです。
